use crate::compressor::macros::make_tag_mapper;

pub struct OsmMapBuilding {
    building_type: BuildingType,
}

fn f(s: &BuildingType) -> u8 {
    *s as u8
}

make_tag_mapper![
    enum BuildingType(u8);

    building=apartments
    building=barracks
    building=bungalow
    building=cabin
    building=detached
    building=dormitory
    building=farm
    building=ger
    building=hotel
    building=house
    building=houseboat
    building=residential
    building=semidetached_house
    building=static_caravan
    building=stilt_house
    building=terrace
    building=tree_house
    building=trullo
    building=commercial
    building=industrial
    building=kiosk
    building=office
    building=retail
    building=supermarket
    building=warehouse
    building=religious
    building=cathedral
    building=chapel
    building=church
    building=kingdom_hall
    building=monastery
    building=mosque
    building=presbytery
    building=shrine
    building=synagogue
    building=temple
    building=bakehouse
    building=bridge
    building=civic
    building=college
    building=fire_station
    building=government
    building=gatehouse
    building=hospital
    building=kindergarten
    building=museum
    building=public
    building=school
    building=toilets
    building=train_station
    building=transportation
    building=university
    building=barn
    building=conservatory
    building=cowshed
    building=farm_auxiliary
    building=greenhouse
    building=slurry_tank
    building=stable
    building=sty
    building=livestock
    building=grandstand
    building=pavilion
    building=riding_hall
    building=sports_hall
    building=sports_centre
    building=stadium
    building=allotment_house
    building=boathouse
    building=hangar
    building=hut
    building=shed
    building=carport
    building=garage
    building=garages
    building=parking
    building=digester
    building=service
    building=tech_cab
    building=transformer_tower
    building=water_tower
    building=storage_tank
    building=silo
    building=beach_hut
    building=bunker
    building=castle
    building=construction
    building=container
    building=guardhouse
    building=military
    building=outbuilding
    building=pagoda
    building=quonset_hut
    building=roof
    building=ruins
    building=tent
    building=tower
    building=windmill
    building=yes
];