[package]
name = "offline-tiny-maps"
version = "0.1.0"
edition = "2021"

default-run = "main"

[dependencies]
bincode = "1.3.3"
concurrent-queue = "2.5.0"
osmpbfreader = "0.16.1"
par-map = "0.1.4"
postgres = "0.19.7"
radix_trie = "0.2.1"
rayon = "1.10.0"
serde = { version = "1.0.204", features = ["derive"] }
sha2 = "0.10.8"
